name: unreal-engine
version: 0.1.0
schema: 1
scm: github.com/pubnub/unreal-engine
changelog: 
  - date: 2024-08-14
    version: 0.1.0
    changes:
      - type: feature
        text: "Initial PubNub Unreal Engine SDK release"
sdks:
  - 
      full-name: Unreal Engine SDK
      short-name: UnrealEngine
      artifacts:
        -
          artifact-type: library
          language: C++
          tier: 2
          tags:
            - Server
          source-repository: https://github.com/pubnub/unreal-engine
          documentation: https://www.pubnub.com/docs/sdks/unreal-engine/
          distributions:
            -
              distribution-type: source-code
              distribution-repository: GitHub release
              package-name: pubnub
              location: https://github.com/pubnub/unreal-engine/releases/tag/0.0.0
              supported-platforms:
                supported-operating-systems:
                  Linux:
                    runtime-version:
                      - Unreal Engine 5
                    minimum-os-version:
                      - Ubuntu 12.04
                    maximum-os-version:
                      - Ubuntu 20.04 LTS
                    target-architecture:
                      - x86-64
                  macOS:
                    runtime-version:
                      - Unreal Engine 5
                    minimum-os-version:
                      - macOS 10.12
                    maximum-os-version:
                      - macOS 11.0.1
                    target-architecture:
                      - x86-64
                  Windows:
                    runtime-version:
                      - Unreal Engine 5
                    minimum-os-version:
                      - Windows Vista Ultimate
                    maximum-os-version:
                      - Windows 10 Home
                    target-architecture:
                      - x86-64
  - 
      full-name: Unreal Engine SDK
      short-name: UnrealEngine
      artifacts:
        -
          artifact-type: plugin
          language: C++
          tags:
            - Server
          tier: 2
          source-repository: https://github.com/pubnub/unreal-engine
          documentation: https://www.pubnub.com/docs/sdks/unreal-engine/
          distributions:
            -
              distribution-type: source-code
              distribution-repository: Unreal Engine Marketplace
              package-name: pubnub
              location: https://www.unrealengine.com/marketplace/en-US/product/pubnub
              supported-platforms:
                supported-operating-systems:
                  Linux:
                    runtime-version:
                      - Unreal Engine 5
                    minimum-os-version:
                      - Ubuntu 12.04
                    maximum-os-version:
                      - Ubuntu 20.04 LTS
                    target-architecture:
                      - x86-64
                  macOS:
                    runtime-version:
                      - Unreal Engine 5
                    minimum-os-version:
                      - macOS 10.12
                    maximum-os-version:
                      - macOS 11.0.1
                    target-architecture:
                      - x86-64
                  Windows:
                    runtime-version:
                      - Unreal Engine 5
                    minimum-os-version:
                      - Windows Vista Ultimate
                    maximum-os-version:
                      - Windows 10 Home
                    target-architecture:
                      - x86-64
features:
  access:
    - ACCESS-OBJECTS-V2-MANAGEMENT
    - ACCESS-SECRET-KEY-ALL-ACCESS
    - ACCESS-GRANT-TOKEN
    - ACCESS-PARSE-TOKEN
    - ACCESS-SET-TOKEN
    - ACCESS-REVOKE-TOKEN
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-SYNC
    - PUBLISH-ASYNC
    - PUBLISH-FIRE
    - PUBLISH-REPLICATION-FLAG
  storage:
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-COUNT
    - STORAGE-REVERSE
    - STORAGE-START-END
    - STORAGE-MESSAGE-COUNT
    - STORAGE-HISTORY-WITH-META
    - STORAGE-FETCH-WITH-META
    - STORAGE-FETCH-WITH-MESSAGE-ACTIONS
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-SIGNAL-LISTENER
    - SUBSCRIBE-USER-LISTENER
    - SUBSCRIBE-SPACE-LISTENER
    - SUBSCRIBE-MEMBERSHIP-LISTENER
    - SUBSCRIBE-MESSAGE-ACTIONS-LISTENER
  signal:
    - SIGNAL-SEND
  objects:
    - OBJECTS-GET-USER
    - OBJECTS-GET-USERS
    - OBJECTS-CREATE-USER
    - OBJECTS-UPDATE-USER
    - OBJECTS-DELETE-USER
    - OBJECTS-GET-SPACE
    - OBJECTS-GET-SPACES
    - OBJECTS-CREATE-SPACE
    - OBJECTS-UPDATE-SPACE
    - OBJECTS-DELETE-SPACE
    - OBJECTS-GET-MEMBERSHIPS
    - OBJECTS-JOIN-SPACES
    - OBJECTS-UPDATE-MEMBERSHIPS
    - OBJECTS-LEAVE-SPACES
    - OBJECTS-GET-MEMBERS
    - OBJECTS-ADD-MEMBERS
    - OBJECTS-UPDATE-MEMBERS
    - OBJECTS-REMOVE-MEMBERS
  message-actions:
    - MESSAGE-ACTIONS-GET
    - MESSAGE-ACTIONS-ADD
    - MESSAGE-ACTIONS-REMOVE
supported-platforms:
  - version: PubNub Unreal Engine SDK
    platforms:
      - Windows
      - Mac OS 
      - Unix 

