name: unreal-engine
schema: 1
version: v0.3.2
scm: github.com/pubnub/unreal-engine
changelog:
  - date: 2025-06-10
    version: v0.3.2
    changes:
      - type: feature
        text: "Add function DeleteMessages which can be used to delete messages from the history."
      - type: feature
        text: "Add function InitPubnubWithConfig which can be used to initialize PubnubSubsystem with custom config, separate from Project Settings."
      - type: improvement
        text: "Add PubSub samples"
      - type: improvement
        text: "Fix compilation warnings"
  - date: 2025-05-27
    version: v0.3.1
    changes:
      - type: feature
        text: "Add new overloads, for all function that return data, with native (not dynamic) delegates that can be used with Lambdas."
      - type: feature
        text: "Add publish/signal message serialization and deserialization - now any string can be send by those methods."
      - type: feature
        text: "Add unit and integration tests for all end points."
      - type: bug
        text: "Fix bug that UserID was not set immediately."
      - type: bug
        text: "Fix bug that only published messages were received from subscription, but not signals and other types."
      - type: bug
        text: "Fix bugs that group operations were sometimes returning previous responses."
      - type: bug
        text: "Fix bug that MessageCounts function was not always returning correct count."
      - type: bug
        text: "Fix incorrect sort and include parameters related to users." 
  - date: 2025-04-29
    version: v0.3.0
    changes:
     - type: feature
       text: "Rework GetMemberships, GetChannelMembers, GetAllUsersMetadataand GetAllChannelsMetadata to have dedicated structures for Include and Sort fields. Note: this is BREAKING CHANGE."
     - type: improvement
       text: "Change subscription loop to use Event Engine."
     - type: improvement
       text: "Mark _JSON functions as deprecated"
     - type: improvement
       text: "Remove not needed C-Core files. Leave only required headers."
     - type: bug
       text: "Fix bugs in parsing FetchHistory response."
     - type: bug
       text: "Fix bug that not all requested data was included in functions response when TotalCount was set."
  - date: 2025-02-12
    version: v0.2.6
    changes:
     - type: bug
       text: "Fix Auth Token related functions."
     - type: bug
       text: "Fix SetSecretKeyAutomatically setting to set the key properly."
     - type: bug
       text: "Fix 'PubnubLog: Error: Pubnub user ID is not set. Aborting operation.' false error."
  - date: 2025-02-06
    version: v0.2.5
    changes:
     - type: feature
       text: "Add plugin support for Linux and IOS projects."
  - date: 2025-01-21
    version: v0.2.4
    changes:
     - type: feature
       text: "Pass logs from c-core to UE sdk."
  - date: 2024-11-28
    version: v0.2.3
    changes:
     - type: bug
       text: "Fix incorrect memberships input object Json checks"
  - date: 2024-11-25
    version: v0.2.2
    changes:
     - type: feature
       text: "Add Unreal 5.5 support"
     - type: feature
       text: "Add documentation in code"
     - type: feature
       text: "Add CustomMessageType parameter to publish, signal and history"
     - type: improvement
       text: "Rename uuid to user in all inputs and functions."
     - type: improvement
       text: "Rename ChannelName to Channel in in function inputs."
  - date: 2024-09-16
    version: v0.1.4
    changes:
     - type: feature
       text: "Add proper MacOS static library"
  - date: 2024-09-13
    version: v0.1.3
    changes:
      - type: feature
        text: "fixes custom version of the C-core library"
  - date: 2024-09-11
    version: v0.1.2
    changes:
      - type: feature
        text: "Fixes for Unreal Engine Marketplace"
  - date: 2024-08-14
    version: v0.1.0
    changes:
      - type: feature
        text: "Initial PubNub Unreal Engine SDK release"
sdks:
  - 
      full-name: Unreal Engine SDK
      short-name: UnrealEngine
      artifacts:
        -
          artifact-type: library
          language: C++
          tier: 2
          tags:
            - Server
          source-repository: https://github.com/pubnub/unreal-engine
          documentation: https://www.pubnub.com/docs/sdks/unreal-engine/
          distributions:
            -
              distribution-type: source-code
              distribution-repository: GitHub release
              package-name: pubnub
              location: https://github.com/pubnub/unreal-engine/releases/tag/0.0.0
              supported-platforms:
                supported-operating-systems:
                  Linux:
                    runtime-version:
                      - Unreal Engine 5
                    minimum-os-version:
                      - Ubuntu 20.04 LTS
                    maximum-os-version:
                      - Ubuntu 24.04 LTS
                    target-architecture:
                      - x86-64
                  macOS:
                    runtime-version:
                      - Unreal Engine 5
                    minimum-os-version:
                      - macOS 12.5
                    maximum-os-version:
                      - macOS 15.5
                    target-architecture:
                      - x86-64
                  Windows:
                    runtime-version:
                      - Unreal Engine 5
                    minimum-os-version:
                      - Windows 10 Home
                    maximum-os-version:
                      - Windows 11 Pro
                    target-architecture:
                      - x86-64
  - 
      full-name: Unreal Engine SDK
      short-name: UnrealEngine
      artifacts:
        -
          artifact-type: plugin
          language: C++
          tags:
            - Server
          tier: 2
          source-repository: https://github.com/pubnub/unreal-engine
          documentation: https://www.pubnub.com/docs/sdks/unreal-engine/
          distributions:
            -
              distribution-type: source-code
              distribution-repository: Unreal Engine Marketplace
              package-name: pubnub
              location: https://www.fab.com/listings/9501a8d6-f9e6-4cf8-8b56-d173bdb71fc4
              supported-platforms:
                supported-operating-systems:
                  Linux:
                    runtime-version:
                      - Unreal Engine 5
                    minimum-os-version:
                      - Ubuntu 20.04 LTS
                    maximum-os-version:
                      - Ubuntu 24.04 LTS
                    target-architecture:
                      - x86-64
                  macOS:
                    runtime-version:
                      - Unreal Engine 5
                    minimum-os-version:
                      - macOS 12.5
                    maximum-os-version:
                      - macOS 15.5
                    target-architecture:
                      - x86-64
                  Windows:
                    runtime-version:
                      - Unreal Engine 5
                    minimum-os-version:
                      - Windows 10 Home
                    maximum-os-version:
                      - Windows 11 Pro
                    target-architecture:
                      - x86-64
features:
  access:
    - ACCESS-OBJECTS-V2-MANAGEMENT
    - ACCESS-SECRET-KEY-ALL-ACCESS
    - ACCESS-GRANT-TOKEN
    - ACCESS-PARSE-TOKEN
    - ACCESS-SET-TOKEN
    - ACCESS-REVOKE-TOKEN
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-SYNC
    - PUBLISH-ASYNC
    - PUBLISH-FIRE
    - PUBLISH-REPLICATION-FLAG
  storage:
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-COUNT
    - STORAGE-REVERSE
    - STORAGE-START-END
    - STORAGE-MESSAGE-COUNT
    - STORAGE-HISTORY-WITH-META
    - STORAGE-FETCH-WITH-META
    - STORAGE-FETCH-WITH-MESSAGE-ACTIONS
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-SIGNAL-LISTENER
    - SUBSCRIBE-USER-LISTENER
    - SUBSCRIBE-SPACE-LISTENER
    - SUBSCRIBE-MEMBERSHIP-LISTENER
    - SUBSCRIBE-MESSAGE-ACTIONS-LISTENER
  signal:
    - SIGNAL-SEND
  objects:
    - OBJECTS-GET-USER
    - OBJECTS-GET-USERS
    - OBJECTS-CREATE-USER
    - OBJECTS-UPDATE-USER
    - OBJECTS-DELETE-USER
    - OBJECTS-GET-SPACE
    - OBJECTS-GET-SPACES
    - OBJECTS-CREATE-SPACE
    - OBJECTS-UPDATE-SPACE
    - OBJECTS-DELETE-SPACE
    - OBJECTS-GET-MEMBERSHIPS
    - OBJECTS-JOIN-SPACES
    - OBJECTS-UPDATE-MEMBERSHIPS
    - OBJECTS-LEAVE-SPACES
    - OBJECTS-GET-MEMBERS
    - OBJECTS-ADD-MEMBERS
    - OBJECTS-UPDATE-MEMBERS
    - OBJECTS-REMOVE-MEMBERS
  message-actions:
    - MESSAGE-ACTIONS-GET
    - MESSAGE-ACTIONS-ADD
    - MESSAGE-ACTIONS-REMOVE
supported-platforms:
  - version: PubNub Unreal Engine SDK
    platforms:
      - Windows
      - Mac OS
      - IOS       
      - Unix 
      - Android 

